// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RumahMakanPadang.dal;

namespace RumahMakanPadang.dal.Migrations
{
    [DbContext(typeof(RumahMakanPadangDbContext))]
    [Migration("20211124005807_added_chef_ktp_foreignkey")]
    partial class added_chef_ktp_foreignkey
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RumahMakanPadang.dal.Models.Chef", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("KTP")
                        .IsRequired()
                        .HasColumnType("nvarchar(16)")
                        .HasMaxLength(16);

                    b.Property<string>("Nama")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Spesialisasi")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int>("Umur")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KTP")
                        .IsUnique();

                    b.ToTable("Chefs");
                });

            modelBuilder.Entity("RumahMakanPadang.dal.Models.Masakan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChefKTP")
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Deskripsi")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int>("Harga")
                        .HasColumnType("int");

                    b.Property<string>("Nama")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("ChefKTP");

                    b.HasIndex("Nama")
                        .IsUnique()
                        .HasFilter("[Nama] IS NOT NULL");

                    b.ToTable("Masakans");
                });

            modelBuilder.Entity("RumahMakanPadang.dal.Models.Masakan", b =>
                {
                    b.HasOne("RumahMakanPadang.dal.Models.Chef", "Chef")
                        .WithMany("Masakans")
                        .HasForeignKey("ChefKTP")
                        .HasPrincipalKey("KTP");
                });
#pragma warning restore 612, 618
        }
    }
}
